[fix] (compilation openjdk): call the method isEmpty instead of checking the attribute length that does not exist
The compilation fails with the error below when using OpenJDK.

~/jnanomsg/src/java/nanomsg/pubsub/SubSocket.java:26:
error: cannot find symbol
    if(topic.length == 0)
               ^
symbol:   variable length
location: variable topic of type String
1 error
Compilation of Java sources(lein javac) failed.

~/jnanomsg(branch:bug/javac*) » java -version
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)